# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            jolidang
tagline:          '졸리당'
description:      'I am  <a href="https://ikju1223.github.io/" target="_blank">ikju</a> and <a href="https://ikju1223.github.io/" target="_blank">jolidang</a>.'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'Ikju'
  url:            https://ikju1223.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
