# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ikju
tagline:          'code'
description:      '.'
url:              'https://github.com/ikju1223'
baseurl:          /

author:
  name:           'Ikju'
  url:            https://ikju1223.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ikju1223/ikju1223.github.io
