# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            ikju
tagline:          'code'
description:      'I am small web engineer. 뭉기는 이걸 보고있으면 셀러리을 흔들어주세요'
url:              'https://github.com/ikju1223'
baseurl:          /

author:
  name:           'Ikju'
  url:            https://ikju1223.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ikju1223/ikju1223.github.io
